[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:dnsmasq]
command=/usr/sbin/dnsmasq --keep-in-foreground --conf-file=/etc/dnsmasq/dnsmasq.conf
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:chrony]
command=/usr/sbin/chronyd -d -f /etc/chrony/chrony.conf
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
